"use client";

import type { components } from "@locallife/shared-types";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArrowLeft, CalendarClock, CheckCircle2, GitBranch, Plus, RefreshCw, Trash2, WalletCards } from "lucide-react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Field, Input, Select } from "@/components/ui/form-controls";
import { PageHeader } from "@/components/ui/page-header";
import { Panel, PanelHeader } from "@/components/ui/panel";
import { ErrorState, SkeletonList } from "@/components/ui/states";
import { addCommitmentLink, getCommitmentAssessment, getPreferences, listCommitmentTimeline, removeCommitmentLink } from "@/lib/api/connected";
import { queryKeys } from "@/lib/api/query-keys";
import { formatDate, formatDateTime, formatDuration, formatMoney } from "@/lib/format";
import { useUiStore } from "@/stores/ui-store";

import { AssessmentStatus, CommitmentStatusBadge, EntityLink } from "./commitment-ui";
import { RelationshipGraph } from "./relationship-graph";
import { ScheduleReview } from "./schedule-review";

type LinkType = components["schemas"]["CommitmentEntityType"];
const tabs = ["overview", "time", "finance", "links", "graph", "timeline"] as const;
type Tab = (typeof tabs)[number];

export function CommitmentDetail({ commitmentId }: { commitmentId: string }) {
  const router = useRouter();
  const params = useSearchParams();
  const tab = (tabs.includes(params.get("tab") as Tab) ? params.get("tab") : "overview") as Tab;
  const assessment = useQuery({ queryKey: queryKeys.commitments.assessment(commitmentId), queryFn: () => getCommitmentAssessment(commitmentId) });
  const timeline = useQuery({ queryKey: queryKeys.commitments.timeline(commitmentId), queryFn: () => listCommitmentTimeline(commitmentId, { page_size: 100 }), enabled: tab === "timeline" });
  const preferences = useQuery({ queryKey: queryKeys.system.preferences, queryFn: getPreferences });
  const [entityType, setEntityType] = useState<LinkType>("task");
  const [entityId, setEntityId] = useState("");
  const queryClient = useQueryClient();
  const pushToast = useUiStore((state) => state.pushToast);
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["commitments", commitmentId] });
  const link = useMutation({ mutationFn: () => addCommitmentLink(commitmentId, { entity_type: entityType, entity_id: entityId, role: "required" }), onSuccess: async () => { setEntityId(""); await refresh(); pushToast({ title: "Record linked", tone: "success" }); }, onError: (error) => pushToast({ title: "Couldn't link record", description: error instanceof Error ? error.message : "Check the record ID.", tone: "error" }) });
  const unlink = useMutation({ mutationFn: (id: string) => removeCommitmentLink(commitmentId, id), onSuccess: async () => { await refresh(); pushToast({ title: "Link removed", tone: "success" }); }, onError: (error) => pushToast({ title: "Couldn't remove link", description: error instanceof Error ? error.message : "Try again.", tone: "error" }) });
  if (assessment.isLoading || preferences.isLoading) return <SkeletonList rows={8} />;
  if (assessment.isError || preferences.isError || !assessment.data || !preferences.data) return <ErrorState retry={() => void Promise.all([assessment.refetch(), preferences.refetch()])} />;
  const data = assessment.data;
  const commitment = data.commitment;
  const impact = data.impact;
  const timezone = preferences.data.timezone;
  const setTab = (next: Tab) => { const query = new URLSearchParams(params.toString()); query.set("tab", next); router.replace(`/commitments/${commitmentId}?${query}`); };
  const componentRows = [["Time capacity", data.time_capacity_status], ["Financial capacity", data.financial_capacity_status], ["Dependencies", data.dependency_status], ["Schedule conflicts", data.schedule_conflict_status], ["Goal impact", data.goal_impact_status], ["Deadline", data.deadline_status]] as const;
  return <div className="space-y-6"><Link className="inline-flex min-h-10 items-center gap-2 rounded-md px-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" href="/commitments"><ArrowLeft aria-hidden="true" className="h-4 w-4" />All commitments</Link><PageHeader eyebrow={commitment.category || "Commitment"} title={commitment.title} description={commitment.description_markdown || "A connected view of the records and constraints behind this obligation."} actions={<><CommitmentStatusBadge status={commitment.status} /><Button loading={assessment.isFetching} onClick={() => void assessment.refetch()} type="button" variant="secondary"><RefreshCw aria-hidden="true" className="h-4 w-4" />Refresh assessment</Button></>} /><div className="grid gap-3 sm:grid-cols-4"><Panel className="p-4"><p className="text-xs text-muted-foreground">Target</p><p className="mt-2 font-semibold">{formatDate(commitment.target_end_at, timezone)}</p></Panel><Panel className="p-4"><p className="text-xs text-muted-foreground">Planned cost</p><p className="mt-2 font-semibold tabular-nums">{commitment.planned_cost_minor !== null && commitment.currency_code ? formatMoney(commitment.planned_cost_minor, commitment.currency_code) : "Not set"}</p></Panel><Panel className="p-4"><p className="text-xs text-muted-foreground">Required time</p><p className="mt-2 font-semibold tabular-nums">{formatDuration(commitment.time_capacity_requirement_minutes)}</p></Panel><Panel className="p-4"><p className="text-xs text-muted-foreground">Warnings</p><p className="mt-2 font-semibold tabular-nums">{data.warnings.length}</p></Panel></div><div className="overflow-x-auto border-b border-border"><div aria-label="Commitment detail sections" className="flex min-w-max gap-1" role="tablist">{tabs.map((value) => <button aria-selected={tab === value} className={`min-h-10 rounded-t-md px-4 text-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${tab === value ? "border-b-2 border-foreground text-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`} key={value} onClick={() => setTab(value)} role="tab" type="button">{value}</button>)}</div></div>
    {tab === "overview" ? <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="space-y-5"><Panel><PanelHeader title="Feasibility components" description="No aggregate score hides the evidence. Each deterministic component remains visible." /><div className="grid gap-3 p-4 sm:grid-cols-2">{componentRows.map(([label, component]) => <div className="rounded-lg bg-muted p-4" key={label}><AssessmentStatus label={label} level={component.status} /><p className="mt-2 text-xs leading-5 text-muted-foreground">{component.summary}</p></div>)}</div></Panel><Panel><PanelHeader title="Warnings and contributing records" description="Open the exact records behind each warning." />{data.warnings.length ? <ul className="divide-y divide-border">{data.warnings.map((warning) => <li className="p-5" key={warning.code}><div className="flex items-start gap-3"><AlertTriangle aria-hidden="true" className={`mt-0.5 h-5 w-5 shrink-0 ${warning.severity === "critical" ? "text-destructive" : "text-warning"}`} /><div><p className="font-medium">{warning.message}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs">{warning.contributing_entities.map((entity) => <EntityLink id={entity.entity_id} key={`${warning.code}:${entity.entity_type}:${entity.entity_id}`} type={entity.entity_type} />)}</div></div></div></li>)}</ul> : <div className="flex min-h-32 items-center gap-3 p-5 text-sm text-success"><CheckCircle2 aria-hidden="true" className="h-5 w-5" />No warnings from the current linked evidence.</div>}</Panel></div><div className="space-y-5"><Panel><PanelHeader title="Assumptions" description="The calculation boundary, stated plainly." /><ul className="space-y-3 p-5">{data.assumptions.map((assumption) => <li className="text-sm leading-6 text-muted-foreground" key={assumption}>— {assumption}</li>)}</ul></Panel><Panel><PanelHeader title="Suggested deterministic actions" description="Rules-based next steps, not advice from an assistant." />{data.suggested_actions.length ? <ul className="space-y-3 p-5">{data.suggested_actions.map((action) => <li className="rounded-lg bg-muted p-4" key={action.code}><p className="font-medium">{action.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{action.reason}</p><div className="mt-2 flex flex-wrap gap-2">{action.contributing_entities.map((entity) => <EntityLink id={entity.entity_id} key={`${action.code}:${entity.entity_type}:${entity.entity_id}`} type={entity.entity_type} />)}</div></li>)}</ul> : <p className="p-5 text-sm text-muted-foreground">No corrective action is suggested for the current evidence.</p>}</Panel></div></div> : null}
    {tab === "time" ? <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><Panel className="p-5"><p className="text-xs text-muted-foreground">Required task work</p><p className="mt-2 text-2xl font-semibold tabular-nums">{formatDuration(impact.time.required_task_duration_minutes)}</p></Panel><Panel className="p-5"><p className="text-xs text-muted-foreground">Scheduled task work</p><p className="mt-2 text-2xl font-semibold tabular-nums">{formatDuration(impact.time.scheduled_task_duration_minutes)}</p></Panel><Panel className="p-5"><p className="text-xs text-muted-foreground">Unscheduled required work</p><p className="mt-2 text-2xl font-semibold tabular-nums">{formatDuration(impact.time.unscheduled_required_work_minutes)}</p></Panel></div><div className="grid gap-5 xl:grid-cols-2"><Panel><PanelHeader title="Dependencies" description="Missing prerequisites and blocked tasks." /><div className="space-y-4 p-5"><div><p className="text-sm font-medium">Missing</p><div className="mt-2 flex flex-wrap gap-2">{impact.dependencies.missing_dependency_ids.length ? impact.dependencies.missing_dependency_ids.map((id) => <EntityLink id={id} key={id} type="task" />) : <Badge tone="success">None</Badge>}</div></div><div><p className="text-sm font-medium">Blocked</p><div className="mt-2 flex flex-wrap gap-2">{impact.dependencies.blocked_task_ids.length ? impact.dependencies.blocked_task_ids.map((id) => <EntityLink id={id} key={id} type="task" />) : <Badge tone="success">None</Badge>}</div></div></div></Panel><Panel><PanelHeader title="Calendar conflicts" description="Effective windows include preparation, travel, and recovery buffers." />{impact.calendar_conflicts.length ? <ul className="divide-y divide-border">{impact.calendar_conflicts.map((conflict) => <li className="p-4 text-sm" key={`${conflict.first_event_id}:${conflict.second_event_id}`}><div className="flex gap-3"><CalendarClock aria-hidden="true" className="h-4 w-4 text-warning" /><div><EntityLink id={conflict.first_event_id} type="calendar_event" /> <span className="text-muted-foreground">overlaps</span> <EntityLink id={conflict.second_event_id} type="calendar_event" /><p className="mt-1 text-xs text-muted-foreground">{formatDateTime(conflict.first_effective_start, timezone)} – {formatDateTime(conflict.first_effective_end, timezone)}</p></div></div></li>)}</ul> : <p className="p-5 text-sm text-muted-foreground">No effective event windows overlap.</p>}</Panel></div><ScheduleReview commitmentId={commitmentId} timezone={timezone} /></div> : null}
    {tab === "finance" ? <div className="space-y-5"><div className="grid gap-4 lg:grid-cols-2">{impact.currencies.length ? impact.currencies.map((currency) => <Panel className="p-5" key={currency.currency}><div className="flex items-center justify-between"><div className="flex items-center gap-2"><WalletCards aria-hidden="true" className="h-5 w-5" /><h3 className="font-semibold">{currency.currency}</h3></div><Badge tone={currency.financial_buffer_violation ? "danger" : "success"}>{currency.financial_buffer_violation ? "Buffer violation" : "Buffer preserved"}</Badge></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-xs text-muted-foreground">Planned cost</dt><dd className="mt-1 font-medium tabular-nums">{formatMoney(currency.planned_cost_minor, currency.currency)}</dd></div><div><dt className="text-xs text-muted-foreground">Actual cost</dt><dd className="mt-1 font-medium tabular-nums">{formatMoney(currency.actual_cost_minor, currency.currency)}</dd></div><div><dt className="text-xs text-muted-foreground">Projected available</dt><dd className="mt-1 font-medium tabular-nums">{formatMoney(currency.projected_available_minor, currency.currency)}</dd></div><div><dt className="text-xs text-muted-foreground">Required buffer</dt><dd className="mt-1 font-medium tabular-nums">{formatMoney(currency.required_financial_buffer_minor, currency.currency)}</dd></div></dl></Panel>) : <Panel className="p-5 text-sm text-muted-foreground">Link planned or posted transactions to calculate financial impact.</Panel>}</div><Panel><PanelHeader title="Budget impact" description="Planned commitment cost against local budget limits." />{impact.budgets.length ? <div className="grid gap-4 p-4 md:grid-cols-2">{impact.budgets.map((budget) => <div className="rounded-lg bg-muted p-4" key={budget.budget_id}><div className="flex items-center justify-between"><p className="font-medium">{budget.name}</p><Badge tone={budget.violation ? "danger" : "success"}>{budget.violation ? "Over limit" : "Within limit"}</Badge></div><p className="mt-3 text-sm tabular-nums">{formatMoney(budget.remaining_after_planned_minor, budget.currency)} remaining after plans</p></div>)}</div> : <p className="p-5 text-sm text-muted-foreground">No linked budget impact.</p>}</Panel></div> : null}
    {tab === "links" ? <div className="grid gap-5 xl:grid-cols-[1fr_22rem]"><Panel><PanelHeader title="Linked entities" description="These are the source records used by the assessment." />{commitment.links.length ? <ul className="divide-y divide-border">{commitment.links.map((item) => <li className="flex min-h-14 items-center justify-between gap-3 px-5 py-3" key={item.id}><div><EntityLink id={item.entity_id} type={item.entity_type} />{item.role ? <p className="mt-1 text-xs text-muted-foreground">Role: {item.role}</p> : null}</div><Button aria-label={`Remove ${item.entity_type} link`} loading={unlink.isPending && unlink.variables === item.id} onClick={() => unlink.mutate(item.id)} size="icon" type="button" variant="ghost"><Trash2 aria-hidden="true" className="h-4 w-4" /></Button></li>)}</ul> : <p className="p-5 text-sm text-muted-foreground">No linked records yet.</p>}</Panel><Panel className="h-fit p-5"><h3 className="text-sm font-semibold">Link by record ID</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">Use the ID shown in a record URL. Workspace and entity type are validated locally.</p><form className="mt-4 space-y-4" onSubmit={(event) => { event.preventDefault(); link.mutate(); }}><Field id="link-entity-type" label="Record type"><Select id="link-entity-type" onChange={(event) => setEntityType(event.target.value as LinkType)} value={entityType}>{["task", "project", "calendar_event", "note", "planned_transaction", "transaction", "budget", "savings_goal", "goal"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</Select></Field><Field id="link-entity-id" label="Record ID" required><Input id="link-entity-id" onChange={(event) => setEntityId(event.target.value)} spellCheck={false} value={entityId} /></Field><Button disabled={!entityId} loading={link.isPending} type="submit"><Plus aria-hidden="true" className="h-4 w-4" />Add link</Button></form></Panel></div> : null}
    {tab === "graph" ? <Panel><PanelHeader title="Relationship graph" description="Warning contributors use the warning border. Select a node to open its record." /><div className="p-4"><RelationshipGraph commitment={commitment} warnings={data.warnings} /><p className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><GitBranch aria-hidden="true" className="h-4 w-4" />Keyboard users can tab through graph nodes; the linked-entities tab provides the same records as a linear list.</p></div></Panel> : null}
    {tab === "timeline" ? <Panel><PanelHeader title="Commitment timeline" description="Changes across every linked domain, newest first." />{timeline.isLoading ? <div className="p-5"><SkeletonList rows={6} /></div> : timeline.data?.data.length ? <ol className="divide-y divide-border">{timeline.data.data.map((item) => <li className="grid gap-3 p-5 sm:grid-cols-[10rem_1fr_auto]" key={item.item_id}><time className="text-xs text-muted-foreground">{formatDateTime(item.occurred_at, timezone)}</time><div><p className="text-sm font-medium">{item.title}</p>{item.summary ? <p className="mt-1 text-xs leading-5 text-muted-foreground">{item.sensitive ? "Sensitive details are hidden. Open the source record to review them." : item.summary}</p> : null}</div><Badge>{item.entity_type.replaceAll("_", " ")}</Badge></li>)}</ol> : <p className="p-5 text-sm text-muted-foreground">No timeline activity for this commitment yet.</p>}</Panel> : null}
  </div>;
}
