export const queryKeys = {
  system: {
    all: ["system"] as const,
    health: ["system", "health"] as const,
    info: ["system", "info"] as const,
    preferences: ["system", "preferences"] as const,
  },
  projects: {
    all: ["projects"] as const,
    list: (filters: object = {}) => ["projects", "list", filters] as const,
  },
  tasks: {
    all: ["tasks"] as const,
    list: (filters: object = {}) => ["tasks", "list", filters] as const,
    detail: (id: string) => ["tasks", "detail", id] as const,
  },
  calendar: {
    all: ["calendar"] as const,
    eventsRoot: ["calendar", "events"] as const,
    events: (range: object) => ["calendar", "events", range] as const,
    conflictsRoot: ["calendar", "conflicts"] as const,
    conflicts: (range: object) => ["calendar", "conflicts", range] as const,
  },
  notes: {
    all: ["notes"] as const,
    list: (filters: object = {}) => ["notes", "list", filters] as const,
    detail: (id: string) => ["notes", "detail", id] as const,
    attachments: (noteId?: string) => ["notes", "attachments", noteId] as const,
    tags: ["notes", "tags"] as const,
  },
  finance: {
    all: ["finance"] as const,
    accounts: ["finance", "accounts"] as const,
    transactions: (filters: object = {}) => ["finance", "transactions", filters] as const,
    planned: (filters: object = {}) => ["finance", "planned", filters] as const,
    categories: ["finance", "categories"] as const,
    budgets: ["finance", "budgets"] as const,
    budgetConsumption: (id: string) => ["finance", "budgets", id, "consumption"] as const,
    cashFlow: (range: object) => ["finance", "reports", "cash-flow", range] as const,
    spending: (range: object) => ["finance", "reports", "spending", range] as const,
    committed: (date: string) => ["finance", "reports", "committed", date] as const,
    subscriptions: ["finance", "subscriptions"] as const,
    savingsGoals: ["finance", "savings-goals"] as const,
  },
  goals: {
    all: ["goals"] as const,
    list: ["goals", "list"] as const,
  },
  commitments: {
    all: ["commitments"] as const,
    list: (filters: object = {}) => ["commitments", "list", filters] as const,
    detail: (id: string) => ["commitments", id, "detail"] as const,
    assessment: (id: string) => ["commitments", id, "assessment"] as const,
    impact: (id: string) => ["commitments", id, "impact"] as const,
    links: (id: string) => ["commitments", id, "links"] as const,
    timeline: (id: string, filters: object = {}) => ["commitments", id, "timeline", filters] as const,
    warnings: (id: string) => ["commitments", id, "warnings"] as const,
  },
  scheduling: {
    capacity: (range: object) => ["scheduling", "capacity", range] as const,
    preview: (id: string) => ["scheduling", "preview", id] as const,
  },
  scenarios: {
    all: ["scenarios"] as const,
    list: ["scenarios", "list"] as const,
    detail: (id: string) => ["scenarios", id, "detail"] as const,
    changes: (id: string) => ["scenarios", id, "changes"] as const,
    preview: (id: string) => ["scenarios", id, "preview"] as const,
    compare: (ids: string[]) => ["scenarios", "compare", ids] as const,
  },
  timeline: {
    all: ["timeline"] as const,
    list: (filters: object = {}) => ["timeline", "list", filters] as const,
  },
  search: (query: string) => ["global-search", query] as const,
} as const;
